//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCheapCartService.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FeaturesId { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public string ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
