//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCheapCartService.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockId { get; set; }
        public int ProductId { get; set; }
        public int StockStatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual StockStatu StockStatu { get; set; }
    }
}
