//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCheapCartService.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserProfileId { get; set; }
        public int UserId { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string HomeContactNumber { get; set; }
        public string OfficeContactNumber { get; set; }
        public string OtherContactNumber { get; set; }
        public Nullable<int> HomeAddress { get; set; }
        public Nullable<int> OfficeAddress { get; set; }
        public Nullable<int> OtherAddress { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
